# fly.toml app configuration file generated for notesapp-microservice on 2023-04-28T22:51:58+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "notesapp-microservice"
primary_region = "ams"

[env]
  PORT = "8080"
  
[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
